baseURL = 'https://hack.lindiana.ca/'
languageCode = 'en-us'
title = 'garden'
#theme = 'ananke'
theme = 'vanilla-bootstrap-hugo-theme'

[taxonomies] 
tags = 'tags'

[menu] 
[[menu.nav]]
name = 'home'
pageRef = '/'
weight = 10
[[menu.nav]] 
name = 'guides' 
pageRef = '/guides' 
weight = 11 
[[menu.nav]] 
name = 'tags' 
pageRef = '/tags'
weight = 12

#[markup]
#  [markup.goldmark]
#    [markup.goldmark.extensions]
#      definitionList = true
#      footnote = true
#      linkify = true
#      linkifyProtocol = 'https'
#      strikethrough = true
#      table = true
#      taskList = true

